# Generated by Django 4.2.3 on 2023-07-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
