# Generated by Django 4.2.3 on 2023-07-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0003_alter_recipe_image_mealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='num_days',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='days',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.CreateModel(
            name='MealDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('meal_type', models.CharField(max_length=20)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeArchive.mealplan')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeArchive.recipe')),
            ],
        ),
    ]
