# Generated by Django 4.2.3 on 2023-07-18 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0005_alter_mealplan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
