# Generated by Django 4.2.3 on 2024-01-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0008_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='generated_images_count',
            field=models.IntegerField(default=0),
        ),
    ]
