# Generated by Django 4.2.3 on 2024-01-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0009_profile_generated_images_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
    ]
