# Generated by Django 4.2.3 on 2024-01-15 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0012_alter_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_generations_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
