# Generated by Django 4.2.3 on 2024-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0013_profile_has_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
