# Generated by Django 4.2.3 on 2024-02-10 14:17

import RecipeArchive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0015_profile_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=RecipeArchive.models.UploadToPathAndRename('recipes')),
        ),
    ]
