# Generated by Django 4.2.3 on 2024-02-11 18:59
from django.db import migrations


def transfer_ingredients_to_instructions(apps, schema_editor):
    Recipe = apps.get_model('RecipeArchive', 'Recipe')
    for recipe in Recipe.objects.all():
        if recipe.instructions:
            recipe.instructions += "\n\nIngredients:\n" + recipe.ingredients
        else:
            recipe.instructions = "Ingredients:\n" + recipe.ingredients
        recipe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0017_recipe_instructions'),
    ]

    operations = [
        migrations.RunPython(transfer_ingredients_to_instructions),
    ]
