# Generated by Django 4.2.3 on 2024-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0020_recipe_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
