# Generated by Django 4.2.3 on 2024-04-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0021_recipe_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='original_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='RecipeArchive.recipe'),
        ),
    ]
