# Generated by Django 4.2.3 on 2024-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeArchive', '0022_recipe_is_original_recipe_original_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='copy_count',
            field=models.IntegerField(default=0),
        ),
    ]
